stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

test:
  stage: test
  script:
    - docker pull $DOCKER_IMAGE
    - docker run --rm $DOCKER_IMAGE pytest /Users/kima/Downloads/Telegram\ Desktop/shuup\ 2/shuup/shuup_tests

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_IMAGE
    - docker run -d -p 8000:8000 $DOCKER_IMAGE
  only:
    - master
