version: "3.7"

volumes:
  prometheus_data:
  grafana_data:

services:
  shuup:
    build:
      context: .
    ports:
      - "8000:8000"
    tty: true
    restart: unless-stopped
  grafana: 
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes: 
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus-data:/prometheus
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    depends_on:
      - shuup
    links:
      - shuup:shuup
    restart: unless-stopped

 
  
  